source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'coffee-script'
gem 'shotgun'
gem 'tweetstream'
gem 'pusher'
gem 'meme_captain'
gem 'google-api-client'
gem 'rest-client'